[local]
localhost

[mongodb]
mongodb.maxdevopstech.online

[redis]
redis.maxdevopstech.online

[mysql]
mysql.maxdevopstech.online

[rabbitmq]
rabbitmq.maxdevopstech.online

[catalogue]
catalogue.maxdevopstech.online

[user]
user.maxdevopstech.online

[cart]
cart.maxdevopstech.online

[shipping]
shipping.maxdevopstech.online

[payment]
payment.maxdevopstech.online

[frontend]
frontend.maxdevopstech.online